package com.fridgetracker.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme — v2 values, taken verbatim from docs/ui-20260718-fridge-tracker-v2.md section 2.1.
// Seed color: #159A66 (cool emerald green), superseding v1's warm #386A46.
val md_theme_light_primary = Color(0xFF159A66)
val md_theme_light_onPrimary = Color(0xFFFBFFFC)
val md_theme_light_primaryContainer = Color(0xFF9EF2C4)
val md_theme_light_onPrimaryContainer = Color(0xFF00210F)
val md_theme_light_secondary = Color(0xFF4C7A63)
val md_theme_light_onSecondary = Color(0xFFFBFFFC)
val md_theme_light_secondaryContainer = Color(0xFFCBF0DC)
val md_theme_light_onSecondaryContainer = Color(0xFF082017)
val md_theme_light_tertiary = Color(0xFF3B6E39)
val md_theme_light_onTertiary = Color(0xFFFBFFFC)
val md_theme_light_tertiaryContainer = Color(0xFFC3EFC0)
val md_theme_light_onTertiaryContainer = Color(0xFF04210A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFBFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5FBF8)
val md_theme_light_onBackground = Color(0xFF151E19)
val md_theme_light_surface = Color(0xFFF5FBF8)
val md_theme_light_onSurface = Color(0xFF151E19)
val md_theme_light_surfaceVariant = Color(0xFFDCE8E0)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4A44)
val md_theme_light_outline = Color(0xFF6F7A73)
val md_theme_light_outlineVariant = Color(0xFFBFCBC3)
val md_theme_light_surfaceContainerLowest = Color(0xFFEFFAF4)
val md_theme_light_surfaceContainerLow = Color(0xFFE9F6EF)
val md_theme_light_surfaceContainer = Color(0xFFE3F1E8)
val md_theme_light_surfaceContainerHigh = Color(0xFFDDEBE1)
val md_theme_light_surfaceContainerHighest = Color(0xFFD7E5DA)

// Custom semantic "warning" tokens (light) — unchanged from v1, not in scope for this pass.
val md_theme_light_warning = Color(0xFF8B5A00)
val md_theme_light_onWarning = Color(0xFFFFFBFF)
val md_theme_light_warningContainer = Color(0xFFFFDDA6)
val md_theme_light_onWarningContainer = Color(0xFF2B1800)

// Dark scheme — v2 direction values from the same section, following the same tone-pairing
// v1 used. Still hand-derived, not run through Material Theme Builder; verify contrast before
// shipping (same caveat the UI doc flags, especially for the new surfaceContainer series).
val md_theme_dark_primary = Color(0xFF7FDBA8)
val md_theme_dark_onPrimary = Color(0xFF003920)
val md_theme_dark_primaryContainer = Color(0xFF00522E)
val md_theme_dark_onPrimaryContainer = Color(0xFF9EF2C4)
val md_theme_dark_secondary = Color(0xFFB0D4C0)
val md_theme_dark_onSecondary = Color(0xFF1B3A2A)
val md_theme_dark_secondaryContainer = Color(0xFF334F41)
val md_theme_dark_onSecondaryContainer = Color(0xFFCBF0DC)
val md_theme_dark_tertiary = Color(0xFFC3D46B)
val md_theme_dark_onTertiary = Color(0xFF2D3900)
val md_theme_dark_tertiaryContainer = Color(0xFF434F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFDDEE9C)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0E1512)
val md_theme_dark_onBackground = Color(0xFFDDE4DF)
val md_theme_dark_surface = Color(0xFF0E1512)
val md_theme_dark_onSurface = Color(0xFFDDE4DF)
val md_theme_dark_surfaceVariant = Color(0xFF3F4A44)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFCBC3)
val md_theme_dark_outline = Color(0xFF899690)
val md_theme_dark_outlineVariant = Color(0xFF3F4A44)
val md_theme_dark_surfaceContainerLowest = Color(0xFF090F0C)
val md_theme_dark_surfaceContainerLow = Color(0xFF151E19)
val md_theme_dark_surfaceContainer = Color(0xFF19221C)
val md_theme_dark_surfaceContainerHigh = Color(0xFF232D26)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2E3830)

// Custom semantic "warning" tokens (dark) — unchanged from v1
val md_theme_dark_warning = Color(0xFFFFBA6C)
val md_theme_dark_onWarning = Color(0xFF452B00)
val md_theme_dark_warningContainer = Color(0xFF633F00)
val md_theme_dark_onWarningContainer = Color(0xFFFFDDA6)
